apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: ajgagal/ticket-tickets
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
          env:
            - name: MONGO_URI
              value: "mongodb://tickets-mongo-srv:27017/ticket-tickets"
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: cookie-secret
                  key: COOKIE_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  type: ClusterIP
  selector:
    app: tickets
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: tickets
