name: tickets-tests

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && npm install && npm run test:ci
